transform:
  target: dev
  outputs:
    dev:
      type: trino
      method: ldap
      host: "{{ env_var('STARBURST_HOST') }}"
      port: "{{ env_var('STARBURST_PORT') }}"
      user: "{{ env_var('STARBURST_USER') }}"
      password: "{{ env_var('STARBURST_PASSWORD') }}"
      catalog: vinty
      schema: dbt_dev
    prod:
      type: trino
      method: ldap
      host: "{{ env_var('STARBURST_HOST') }}"
      port: "{{ env_var('STARBURST_PORT') }}"
      user: "{{ env_var('STARBURST_USER') }}"
      password: "{{ env_var('STARBURST_PASSWORD') }}"
      catalog: vinty
      schema: analytics
